<template>
  <Layout class="j_layout ivu-layout-has-sider j_sitemap">
    <MenuBar :data="'menuStatic'" :active="'sitemap'"/>
    <Layout class="j_layout_content">
      <JHeader :title="'Sitemap生成'" :type="true" :tip="tip" :website="true" @on-layout="layoutChange"/>
      <Content>
        <Button type="info" class="w144" @click="form = true" v-if="!form">开启自定义选项</Button>
        <Button class="info" @click="update" style="width: 97px;" v-if="!form">一键更新</Button>
        <Form ref="modalForm" :model="detail" :rules="rules" :label-width="110" v-if="form">
          <FormItem label="指定域名：" prop="domain">
            <Input v-model="detail.domain" placeholder="pc.jihui88.com/rest/site/96/index">
              <span slot="prepend">http://</span>
            </Input>
          </FormItem>
          <div class="j_form_title">robots.txt</div>
          <FormItem label="robots.txt：">
            <Input v-model="detail.robots" type="textarea"></Input>
            <Button class="submit" @click="robots">生成</Button>
          </FormItem>
          <div class="j_form_title">Sitemap</div>
          <FormItem label="修改频率：">
            <Select v-model="selectDate" class="w144 border">
              <Option value="always">经常</Option>
              <Option value="hourly">每小时</Option>
              <Option value="daily">每天</Option>
              <Option value="weekly">每周</Option>
              <Option value="monthly">每月</Option>
              <Option value="yearly">每年</Option>
              <Option value="never">从不</Option>
            </Select>
            <Button class="submit" @click="sitemap">生成</Button>
          </FormItem>
          <FormItem label="修改日期：">
            <RadioGroup v-model="detail.lastmod">
              <Radio label="01">使用原始信息</Radio>
              <Radio label="02">统一成当前日期</Radio>
              <Radio label="03">统一成指定日期</Radio>
              <DatePicker type="date" v-model="lastmod" @on-change="lastmod=$event" style="width: 155px;"></DatePicker>
            </RadioGroup>
          </FormItem>
          <FormItem label="优先级：">
            <RadioGroup v-model="detail.priority">
              <Radio label="01">自动调整</Radio>
            </RadioGroup><br/>
            <Input v-model="detail.sitemap" type="textarea"></Input>
          </FormItem>
          <FormItem>
            <Button type="primary" @click="submit">保存修改</Button>
            <Button @click="form = false">关闭</Button>
          </FormItem>
        </Form>

        <hr/>
        <p class="j_sitemap_tip">
          一般来说，搜索引擎蜘蛛（Spider）会跟着链接爬行到你网站的所有网页。<br/>
          但是很多时候，由于种种原因，并不是所有网页都能被收录进搜索引擎数据库。<br/>
          Sitemap就允许站长提供给搜索引擎一个网站地图，列出你所有需要被抓取的网页及重要性级别。
        </p>
        <Button class="info" @click="url('/seo_batch')">批量提交Sitemap</Button>
      </Content>
    </Layout>
  </Layout>
</template>

<script>
import qs from 'qs'
import { mapState } from 'vuex'
import MenuBar from '@/components/common/menu_bar'
import JHeader from '@/components/group/j-header'
export default {
  components: {
    MenuBar,
    JHeader
  },
  data () {
    return {
      tip: '本工具能提供以下功能：<br/>1、一个符合0.90国际规范的Sitemap文件<br/>2、一个能引导搜索引擎蜘蛛（Spider）发现网站地图的robots.txt文件<br/>3、向各大搜索引擎提交Sitemap的快捷入口',
      form: false,
      detail: {
        domain: 'pc.jihui88.com/rest/site/' + this.$store.state.layoutId + '/index',
        robots: '#Robots.txt automatically generated by' + this.$store.state.user.username + '\n\n Sitemap: http://' + this.$store.state.user.username + '/sitemap.xml',
        sitemap: '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n</urlset>',
        lastmod: '01',
        priority: '01'
      },
      selectDate: 'always',
      lastmod: '2015-11-04',
      rules: {
        domain: [
          { required: true, message: '域名不能为空', trigger: 'blur' }
        ]
      }
    }
  },
  computed: {
    ...mapState({
      staticList: state => state.status.staticList
    })
  },
  created () {
    this.layoutChange(this.$store.state.layoutId)
  },
  methods: {
    layoutChange (e) {
      this.staticList.forEach(item => {
        if (item.layoutId === e && item.bind.address) {
          this.detail.domain = item.bind.address
        }
      })
    },
    dateme (date, i) {
      var dateme
      if (this.detail.lastmod === '01') {
        dateme = typeof data !== 'undefined' ? new Date(date[i]) : null
      }
      if (this.detail.lastmod === '02') {
        dateme = new Date()
      }
      if (this.detail.lastmod === '03') {
        dateme = new Date(this.lastmod)
      }
      if (!dateme) {
        return null
      }
      var month = dateme.getMonth() + 1
      if (month < 10) { month = '0' + month }
      var day = dateme.getDate()
      if (day < 10) { day = '0' + day }
      return dateme.getFullYear() + '-' + month + '-' + day
    },
    scaleme (i) {
      if (i === 0) {
        return '1.0000'
      } else if (i === 1) {
        return '0.5000'
      } else if (i === 2) {
        return '0.2500'
      } else {
        return '0.1000'
      }
    },
    sitemap () {
      var ctx = this
      this.$http.get('/rest/api/seotools/sitemapcap').then((res) => {
        var sitemap = ''
        if (res !== null) {
          var filename = res['filename']
          var date = res['date']
          var scale = res['scale']
          sitemap = unescape('%3C%3Fxml%20version%3D%221.0%22%20encoding%3D%22UTF-8%22%3F%3E%0A%3Curlset%20xmlns%3D%22http%3A//www.sitemaps.org/schemas/sitemap/0.9%22%3E%0A')
          for (var i = 0; i < filename.length; i++) {
            sitemap += '<url> \n'
            sitemap += '\t<loc>http://' + ctx.detail.domain + '/' + filename[i] + '</loc> \n'
            sitemap += '\t<lastmod>' + ctx.dateme(date, i) + '</lastmod> \n'
            sitemap += '\t<changefreq>' + ctx.selectDate + '</changefreq> \n'
            sitemap += '\t<priority>' + ctx.scaleme(scale[i]) + '</priority> \n'
            sitemap += '</url> \n'
          }
          sitemap += unescape('%3C/urlset%3E%0A')
          ctx.detail.sitemap = sitemap
        }
        ctx.$http.post('/rest/api/seotools/saveRobotsOrSitemap', qs.stringify({
          content: sitemap,
          type: 'sitemap',
          robotsurl: ctx.detail.domain,
          robots: ctx.detail.robots,
          domain: ctx.detail.domain.trim(),
          freq: ctx.selectDate,
          lastmod: ctx.dateme(null),
          layoutId: ctx.$store.state.layoutId
        })).then((res) => {
          ctx.$Message.success('生成成功!')
        })
      })
    },
    update () {
      this.robots()
      this.sitemap()
    },
    robots () {
      var robots
      var domain = this.detail.domain
      robots = '#Robots.txt automatically generated by\t' + domain + '\n'
      robots += '\n'
      robots += 'Sitemap: http://' + domain + '/sitemap.xml\n'
      this.detail.robots = robots
      this.$http.post('/rest/api/seotools/saveRobotsOrSitemap', qs.stringify({
        content: robots,
        type: 'robots',
        robotsurl: domain,
        layoutId: this.$store.state.layoutId
      })).then((res) => {
        this.$Message.success('生成成功!')
      })
    },
    submit () {
      this.$refs['modalForm'].validate((valid) => {
        if (valid) {
          this.$http.post('/rest/api/seotools/save', qs.stringify({
            robots: this.detail.robots,
            sitemap: this.detail.sitemap,
            domain: this.detail.domain.trim()
          })).then((res) => {
            this.$Message.success(res)
          })
        }
      })
    }
  }
}
</script>

<style lang="less">
.j_sitemap{
  .j_sitemap_tip{
    color: #9c9c9c;
    line-height: 2;
    padding-bottom: 20px;
  }
  hr{
    margin-top: 70px;
  }
  .j_head .j_tip{
    line-height: 2;
  }
}
</style>
